spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: trainingenrollment-service
    spring:
      application:
        name: trainingenrollment-service
      config:
        import: optional:configserver:http://localhost:8888

    server:
      port: 8091

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka

    spring.mail:
      host: smtp.gmail.com
      port: 587
      username: daoudwissal2000@gmail.com
      password: fuyi rvnp vkut gylu
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true

