spring:
  application:
    name: Complaint
  datasource:
    url: jdbc:mysql://localhost:3306/Complaints_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true