server:
  port: 8222  # Port de l'API Gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Active la découverte dynamique via Eureka

      routes:
        - id: internshipoffer-service
          uri: lb://internshipoffer-service
          predicates:
            - Path=/api/v1/internships/**  # Pour les offres de stage
        - id: internshipapplication-service
          uri: lb://internshipoffer-service   # Même microservice, car les candidatures sont gérées ici
          predicates:
            - Path=/api/v1/internship-applications/**  # Pour les candidatures

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
